### ISSUE TITLE
Cannot run composer

### ISSUE THREAD

**Issue by hieu-luu-niteco** [rapidez/rapidez#64]
When I type docker-compose up -d,  the build process causes error as below,  could you please help

```
 Problem 1
#0 5.390     - Only one of these can be installed: illuminate/events[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev], laravel/framework[v10.10.0, ..., 10.x-dev]. laravel/framework replaces illuminate/events and thus cannot coexist with it.
#0 5.390     - rapidez/core[0.93.0, ..., 0.x-dev] require illuminate/events ^9.0 -> satisfiable by illuminate/events[v9.0.0-beta.1, ..., 9.x-dev].
#0 5.390     - Root composer.json requires rapidez/core ~0.93 -> satisfiable by rapidez/core[0.93.0, 0.x-dev].
#0 5.390     - Root composer.json requires laravel/framework ^10.10 -> satisfiable by laravel/framework[v10.10.0, ..., 10.x-dev].
```

**Comment by hieu-luu-niteco** [comment]
> 

thanks @royduin . It works now.  However,  after running,  the Magento and Elastic container keep restarting. 
And accessing http://localhost return 404
![2023-09-11_104526](https://github.com/rapidez/rapidez/assets/18063810/8cd4fbc9-8df1-4336-98b9-71c219aae305)

**Comment by royduin** [comment]
That could be a memory issue; we recommend 4GB+ see: https://docs.rapidez.io/0.x/installation.html#demo-magento-2-webshop
