### ISSUE TITLE
query_shard_exception from Elasticsearch query on product listing pages

### ISSUE THREAD

**Issue by mmbaig-cd** [rapidez/rapidez#72]
Hi, I have installed and setup rapidez instance on my local and connected it with a Magento 2.4.6 instance which is also installed locally and has sample data. Whenever I open a page that contains product listing, for example category page, I get this error for all the product attributes (except price) which are added in the layered navigation from elasticsearch.

Error:
```Container-d00219f7-f813569f.js:1 {"took":5,"responses":[{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: class org.elasticsearch.index.mapper.flattened.FlattenedFieldMapper$KeyedFlattenedFieldData cannot be cast to class org.elasticsearch.index.fielddata.IndexNumericFieldData (org.elasticsearch.index.mapper.flattened.FlattenedFieldMapper$KeyedFlattenedFieldData and org.elasticsearch.index.fielddata.IndexNumericFieldData are in unnamed module of loader 'app')","index_uuid":"WIfIfZkCTcK1i4itRnZd5w","index":"rapidez_products_1_20240521190453"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"rapidez_products_1_20240521190453","node":"ino0urf-SKq9iJnz0zv-xA","reason":{"type":"query_shard_exception","reason":"failed to create query: class org.elasticsearch.index.mapper.flattened.FlattenedFieldMapper$KeyedFlattenedFieldData cannot be cast to class org.elasticsearch.index.fielddata.IndexNumericFieldData (org.elasticsearch.index.mapper.flattened.FlattenedFieldMapper$KeyedFlattenedFieldData and org.elasticsearch.index.fielddata.IndexNumericFieldData are in unnamed module of loader 'app')","index_uuid":"WIfIfZkCTcK1i4itRnZd5w","index":"rapidez_products_1_20240521190453","caused_by":{"type":"class_cast_exception","reason":"class org.elasticsearch.index.mapper.flattened.FlattenedFieldMapper$KeyedFlattenedFieldData cannot be cast to class org.elasticsearch.index.fielddata.IndexNumericFieldData (org.elasticsearch.index.mapper.flattened.FlattenedFieldMapper$KeyedFlattenedFieldData and org.elasticsearch.index.fielddata.IndexNumericFieldData are in unnamed module of loader 'app')"}}}]},"status":400}]}```

<img width="1279" alt="Screenshot 2024-05-22 at 8 16 31 AM" src="https://github.com/rapidez/rapidez/assets/170527608/2dfda0f0-5bb0-4e21-b114-2c1e36c99f04">

<img width="1280" alt="Screenshot 2024-05-22 at 8 17 29 AM" src="https://github.com/rapidez/rapidez/assets/170527608/b5d1b6b6-ee6b-4052-8f5f-e7689a0e9c3b">

Here is my infrastructure info:
- Elasticsearch -> elasticsearch-full, v7.17.4
- PHP -> 8.1
- MacOS
- Valet-plus
- Magento 2.4.6 (also tried with Magento 2.4.7) with flat tables enabled
- MySQL 5.7.44

**Comment by royduin** [comment]
Whoeps, forgot to tag a new 1.x version. It should be fixed in: https://github.com/rapidez/core/releases/tag/1.16.0 containing this PR: https://github.com/rapidez/core/pull/467

**Comment by royduin** [comment]
You're welcome, if you've any other questions we're happy to help. We're also available on Slack: https://rapidez.io/slack
